# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NFCollection")

model.instance <- NFCollection$new()

test_that("hits", {
  # tests for the property `hits` (array[NFReturn])

  # uncomment below to test the property 
  #expect_equal(model.instance$`hits`, "EXPECTED_RESULT")
})

