# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Sample")

model.instance <- Sample$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("hash", {
  # tests for the property `hash` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hash`, "EXPECTED_RESULT")
})

