# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NFReturn")

model.instance <- NFReturn$new()

test_that("run_name", {
  # tests for the property `run_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`run_name`, "EXPECTED_RESULT")
})

test_that("run_id", {
  # tests for the property `run_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`run_id`, "EXPECTED_RESULT")
})

test_that("event", {
  # tests for the property `event` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`event`, "EXPECTED_RESULT")
})

test_that("utc_time", {
  # tests for the property `utc_time` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`utc_time`, "EXPECTED_RESULT")
})

test_that("trace", {
  # tests for the property `trace` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`trace`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("event_id", {
  # tests for the property `event_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`event_id`, "EXPECTED_RESULT")
})

