---
title: "Getting Started"
author: "Sean Davis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Initialize an API Client

```{r}
library(dplyr)
library(metagenomicsClientR)
```


```{r}
basePath = 'https://cmgd-telemetry-whnnxetv4q-uc.a.run.app'
client = ApiClient$new(basePath = basePath)
api = DefaultApi$new(apiClient = client)
```

```{r}
api
```

```{r}

api$GetSamplesMetadataSamplesGet()

api$GetUuidFromStringMetadataUuidGet(string = "Asnicar_2021")

api$SamplesForStudyMetadataStudiesUuidSamplesGet(uuid = "b3416924-2c11-519b-95ba-42d388114c5f")




```







# Queries

```{r}
qres = api$ListFileEventsFilesChangesGet()
qres
```

Convert to data.frame

```{r}
hit_list = qres$toJSON()$hits
df = bind_rows(hit_list)
```

```{r}
glimpse(df)
```

# Models

```{r}
class(qres)
```

```{r}
class(qres$hits[[1]])
```

```{r}
StorageEventReturn
```

```{r}
StorageEventCollection
```

