# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NFCollection
#'
#' @description NFCollection Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field hits Hits list( \link{NFReturn} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NFCollection <- R6::R6Class(
  'NFCollection',
  public = list(
    `hits` = NULL,
    initialize = function(
        `hits`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`hits`)) {
        stopifnot(is.vector(`hits`), length(`hits`) != 0)
        sapply(`hits`, function(x) stopifnot(R6::is.R6(x)))
        self$`hits` <- `hits`
      }
    },
    toJSON = function() {
      NFCollectionObject <- list()
      if (!is.null(self$`hits`)) {
        NFCollectionObject[['hits']] <-
          lapply(self$`hits`, function(x) x$toJSON())
      }

      NFCollectionObject
    },
    fromJSON = function(NFCollectionJson) {
      NFCollectionObject <- jsonlite::fromJSON(NFCollectionJson)
      if (!is.null(NFCollectionObject$`hits`)) {
        self$`hits` <- ApiClient$new()$deserializeObj(NFCollectionObject$`hits`, "array[NFReturn]", loadNamespace("metagenomicsClientR2"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`hits`)) {
        sprintf(
        '"hits":
        [%s]
',
        paste(sapply(self$`hits`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NFCollectionJson) {
      NFCollectionObject <- jsonlite::fromJSON(NFCollectionJson)
      self$`hits` <- ApiClient$new()$deserializeObj(NFCollectionObject$`hits`, "array[NFReturn]", loadNamespace("metagenomicsClientR2"))
      self
    }
  )
)

