# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NFModel
#'
#' @description NFModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field run_name Run Name character 
#'
#' @field run_id Run Id character 
#'
#' @field event Event character 
#'
#' @field utc_time Utc Time character 
#'
#' @field trace Trace object [optional]
#'
#' @field metadata Metadata object [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NFModel <- R6::R6Class(
  'NFModel',
  public = list(
    `run_name` = NULL,
    `run_id` = NULL,
    `event` = NULL,
    `utc_time` = NULL,
    `trace` = NULL,
    `metadata` = NULL,
    initialize = function(
        `run_name`, `run_id`, `event`, `utc_time`, `trace`=NULL, `metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`run_name`)) {
        stopifnot(is.character(`run_name`), length(`run_name`) == 1)
        self$`run_name` <- `run_name`
      }
      if (!missing(`run_id`)) {
        stopifnot(is.character(`run_id`), length(`run_id`) == 1)
        self$`run_id` <- `run_id`
      }
      if (!missing(`event`)) {
        stopifnot(is.character(`event`), length(`event`) == 1)
        self$`event` <- `event`
      }
      if (!missing(`utc_time`)) {
        stopifnot(is.character(`utc_time`), length(`utc_time`) == 1)
        self$`utc_time` <- `utc_time`
      }
      if (!is.null(`trace`)) {
        self$`trace` <- `trace`
      }
      if (!is.null(`metadata`)) {
        self$`metadata` <- `metadata`
      }
    },
    toJSON = function() {
      NFModelObject <- list()
      if (!is.null(self$`run_name`)) {
        NFModelObject[['run_name']] <-
          self$`run_name`
      }
      if (!is.null(self$`run_id`)) {
        NFModelObject[['run_id']] <-
          self$`run_id`
      }
      if (!is.null(self$`event`)) {
        NFModelObject[['event']] <-
          self$`event`
      }
      if (!is.null(self$`utc_time`)) {
        NFModelObject[['utc_time']] <-
          self$`utc_time`
      }
      if (!is.null(self$`trace`)) {
        NFModelObject[['trace']] <-
          self$`trace`
      }
      if (!is.null(self$`metadata`)) {
        NFModelObject[['metadata']] <-
          self$`metadata`
      }

      NFModelObject
    },
    fromJSON = function(NFModelJson) {
      NFModelObject <- jsonlite::fromJSON(NFModelJson)
      if (!is.null(NFModelObject$`run_name`)) {
        self$`run_name` <- NFModelObject$`run_name`
      }
      if (!is.null(NFModelObject$`run_id`)) {
        self$`run_id` <- NFModelObject$`run_id`
      }
      if (!is.null(NFModelObject$`event`)) {
        self$`event` <- NFModelObject$`event`
      }
      if (!is.null(NFModelObject$`utc_time`)) {
        self$`utc_time` <- NFModelObject$`utc_time`
      }
      if (!is.null(NFModelObject$`trace`)) {
        self$`trace` <- NFModelObject$`trace`
      }
      if (!is.null(NFModelObject$`metadata`)) {
        self$`metadata` <- NFModelObject$`metadata`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`run_name`)) {
        sprintf(
        '"run_name":
          "%s"
                ',
        self$`run_name`
        )},
        if (!is.null(self$`run_id`)) {
        sprintf(
        '"run_id":
          "%s"
                ',
        self$`run_id`
        )},
        if (!is.null(self$`event`)) {
        sprintf(
        '"event":
          "%s"
                ',
        self$`event`
        )},
        if (!is.null(self$`utc_time`)) {
        sprintf(
        '"utc_time":
          "%s"
                ',
        self$`utc_time`
        )},
        if (!is.null(self$`trace`)) {
        sprintf(
        '"trace":
          "%s"
                ',
        self$`trace`
        )},
        if (!is.null(self$`metadata`)) {
        sprintf(
        '"metadata":
          "%s"
                ',
        self$`metadata`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NFModelJson) {
      NFModelObject <- jsonlite::fromJSON(NFModelJson)
      self$`run_name` <- NFModelObject$`run_name`
      self$`run_id` <- NFModelObject$`run_id`
      self$`event` <- NFModelObject$`event`
      self$`utc_time` <- NFModelObject$`utc_time`
      self$`trace` <- NFModelObject$`trace`
      self$`metadata` <- NFModelObject$`metadata`
      self
    }
  )
)

