# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NFReturn
#'
#' @description NFReturn Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field run_name Run Name character 
#'
#' @field run_id Run Id character 
#'
#' @field event Event character 
#'
#' @field utc_time Utc Time character 
#'
#' @field trace Trace object [optional]
#'
#' @field metadata Metadata object [optional]
#'
#' @field event_id Event Id integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NFReturn <- R6::R6Class(
  'NFReturn',
  public = list(
    `run_name` = NULL,
    `run_id` = NULL,
    `event` = NULL,
    `utc_time` = NULL,
    `trace` = NULL,
    `metadata` = NULL,
    `event_id` = NULL,
    initialize = function(
        `run_name`, `run_id`, `event`, `utc_time`, `event_id`, `trace`=NULL, `metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`run_name`)) {
        stopifnot(is.character(`run_name`), length(`run_name`) == 1)
        self$`run_name` <- `run_name`
      }
      if (!missing(`run_id`)) {
        stopifnot(is.character(`run_id`), length(`run_id`) == 1)
        self$`run_id` <- `run_id`
      }
      if (!missing(`event`)) {
        stopifnot(is.character(`event`), length(`event`) == 1)
        self$`event` <- `event`
      }
      if (!missing(`utc_time`)) {
        stopifnot(is.character(`utc_time`), length(`utc_time`) == 1)
        self$`utc_time` <- `utc_time`
      }
      if (!missing(`event_id`)) {
        stopifnot(is.numeric(`event_id`), length(`event_id`) == 1)
        self$`event_id` <- `event_id`
      }
      if (!is.null(`trace`)) {
        self$`trace` <- `trace`
      }
      if (!is.null(`metadata`)) {
        self$`metadata` <- `metadata`
      }
    },
    toJSON = function() {
      NFReturnObject <- list()
      if (!is.null(self$`run_name`)) {
        NFReturnObject[['run_name']] <-
          self$`run_name`
      }
      if (!is.null(self$`run_id`)) {
        NFReturnObject[['run_id']] <-
          self$`run_id`
      }
      if (!is.null(self$`event`)) {
        NFReturnObject[['event']] <-
          self$`event`
      }
      if (!is.null(self$`utc_time`)) {
        NFReturnObject[['utc_time']] <-
          self$`utc_time`
      }
      if (!is.null(self$`trace`)) {
        NFReturnObject[['trace']] <-
          self$`trace`
      }
      if (!is.null(self$`metadata`)) {
        NFReturnObject[['metadata']] <-
          self$`metadata`
      }
      if (!is.null(self$`event_id`)) {
        NFReturnObject[['event_id']] <-
          self$`event_id`
      }

      NFReturnObject
    },
    fromJSON = function(NFReturnJson) {
      NFReturnObject <- jsonlite::fromJSON(NFReturnJson)
      if (!is.null(NFReturnObject$`run_name`)) {
        self$`run_name` <- NFReturnObject$`run_name`
      }
      if (!is.null(NFReturnObject$`run_id`)) {
        self$`run_id` <- NFReturnObject$`run_id`
      }
      if (!is.null(NFReturnObject$`event`)) {
        self$`event` <- NFReturnObject$`event`
      }
      if (!is.null(NFReturnObject$`utc_time`)) {
        self$`utc_time` <- NFReturnObject$`utc_time`
      }
      if (!is.null(NFReturnObject$`trace`)) {
        self$`trace` <- NFReturnObject$`trace`
      }
      if (!is.null(NFReturnObject$`metadata`)) {
        self$`metadata` <- NFReturnObject$`metadata`
      }
      if (!is.null(NFReturnObject$`event_id`)) {
        self$`event_id` <- NFReturnObject$`event_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`run_name`)) {
        sprintf(
        '"run_name":
          "%s"
                ',
        self$`run_name`
        )},
        if (!is.null(self$`run_id`)) {
        sprintf(
        '"run_id":
          "%s"
                ',
        self$`run_id`
        )},
        if (!is.null(self$`event`)) {
        sprintf(
        '"event":
          "%s"
                ',
        self$`event`
        )},
        if (!is.null(self$`utc_time`)) {
        sprintf(
        '"utc_time":
          "%s"
                ',
        self$`utc_time`
        )},
        if (!is.null(self$`trace`)) {
        sprintf(
        '"trace":
          "%s"
                ',
        self$`trace`
        )},
        if (!is.null(self$`metadata`)) {
        sprintf(
        '"metadata":
          "%s"
                ',
        self$`metadata`
        )},
        if (!is.null(self$`event_id`)) {
        sprintf(
        '"event_id":
          %d
                ',
        self$`event_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NFReturnJson) {
      NFReturnObject <- jsonlite::fromJSON(NFReturnJson)
      self$`run_name` <- NFReturnObject$`run_name`
      self$`run_id` <- NFReturnObject$`run_id`
      self$`event` <- NFReturnObject$`event`
      self$`utc_time` <- NFReturnObject$`utc_time`
      self$`trace` <- NFReturnObject$`trace`
      self$`metadata` <- NFReturnObject$`metadata`
      self$`event_id` <- NFReturnObject$`event_id`
      self
    }
  )
)

