# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Sample
#'
#' @description Sample Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name Name character 
#'
#' @field hash Hash character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Sample <- R6::R6Class(
  'Sample',
  public = list(
    `name` = NULL,
    `hash` = NULL,
    initialize = function(
        `name`, `hash`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`hash`)) {
        stopifnot(is.character(`hash`), length(`hash`) == 1)
        self$`hash` <- `hash`
      }
    },
    toJSON = function() {
      SampleObject <- list()
      if (!is.null(self$`name`)) {
        SampleObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`hash`)) {
        SampleObject[['hash']] <-
          self$`hash`
      }

      SampleObject
    },
    fromJSON = function(SampleJson) {
      SampleObject <- jsonlite::fromJSON(SampleJson)
      if (!is.null(SampleObject$`name`)) {
        self$`name` <- SampleObject$`name`
      }
      if (!is.null(SampleObject$`hash`)) {
        self$`hash` <- SampleObject$`hash`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`hash`)) {
        sprintf(
        '"hash":
          "%s"
                ',
        self$`hash`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SampleJson) {
      SampleObject <- jsonlite::fromJSON(SampleJson)
      self$`name` <- SampleObject$`name`
      self$`hash` <- SampleObject$`hash`
      self
    }
  )
)

