# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Study
#'
#' @description Study Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name Name character 
#'
#' @field pubmed Pubmed integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Study <- R6::R6Class(
  'Study',
  public = list(
    `name` = NULL,
    `pubmed` = NULL,
    initialize = function(
        `name`, `pubmed`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`pubmed`)) {
        stopifnot(is.numeric(`pubmed`), length(`pubmed`) == 1)
        self$`pubmed` <- `pubmed`
      }
    },
    toJSON = function() {
      StudyObject <- list()
      if (!is.null(self$`name`)) {
        StudyObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`pubmed`)) {
        StudyObject[['pubmed']] <-
          self$`pubmed`
      }

      StudyObject
    },
    fromJSON = function(StudyJson) {
      StudyObject <- jsonlite::fromJSON(StudyJson)
      if (!is.null(StudyObject$`name`)) {
        self$`name` <- StudyObject$`name`
      }
      if (!is.null(StudyObject$`pubmed`)) {
        self$`pubmed` <- StudyObject$`pubmed`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`pubmed`)) {
        sprintf(
        '"pubmed":
          %d
                ',
        self$`pubmed`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StudyJson) {
      StudyObject <- jsonlite::fromJSON(StudyJson)
      self$`name` <- StudyObject$`name`
      self$`pubmed` <- StudyObject$`pubmed`
      self
    }
  )
)

